# This content is generated by {GENERATOR}
#load("@rules_name_of_external//toolchains/lipo:toolchain.bzl", "lipo_toolchain")
load("@//toolchains/lipo:toolchain.bzl", "lipo_toolchain")

lipo_toolchain(
    name = "lipo_auto",
    path = "{LIPO_PATH}",
)

toolchain(
    name = "lipo_auto_toolchain",
    toolchain = ":lipo_auto",
    #toolchain_type = "@rules_name_of_external//toolchains/lipo:toolchain_type",
    toolchain_type = "@//toolchains/lipo:toolchain_type",
)
