name: Bazel build

env:
  HOMEBREW_NO_AUTO_UPDATE: 1
  # typically used for bazel internal testing: changes outputRoot, sets idletimeout to ~15s
  TEST_TMPDIR: /tmp/bazel

# yamllint disable-line rule:truthy
on: [push]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [self-macos-amd64]
        #os: [macos-latest, macos-12, macos-11]
    steps:
      - run: echo "/usr/local/bin" >> $GITHUB_PATH  # uses local python3 as chicken-and-egg resolver, needs to be in path
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
        # ...because now running locally, need to install the binary where the build user can see it
      - run: mkdir -p "${TEST_TMPDIR}"
      - run: env | sort
      - name: Mount bazel cache  # Optional
        uses: actions/cache@v3
        with:
          # needs to be an absolute path, not a variable; I've made it match TEST_TMPDIR above
          path: /tmp/bazel
          key: _bazel_runner
      - run: bazel build //...
      - run: bazel test //...
