name: Conventional Commits

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Conventional Commits
    runs-on: self-macos-amd64
    steps:
      - uses: actions/checkout@v3

      - uses: webiny/action-conventional-commits@v1.1.0
